# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.2.0'

In [2]:
# 1. Read file
data = pd.read_csv("./tic-tac-toe.csv")
data.head(5)

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
# 2. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
data.describe()
data.dtypes

# Check for unique values in all columns
for column in list(data.columns):
    column = list(set(data[column]))
    print(column)

['o', 'b', 'x']
['o', 'b', 'x']
['o', 'b', 'x']
['o', 'b', 'x']
['b', 'o', 'x']
['b', 'o', 'x']
['o', 'b', 'x']
['b', 'o', 'x']
['b', 'o', 'x']
[False, True]

In [4]:
# 3. Convert the categorical values to numeric in all columns.
class_dict = {
    'x': 1,
    'o': 0,
    'b': 2,
}

cols = data[data.columns.difference(["class"])]
for column in cols:
    data[column].replace(class_dict, inplace=True)
    data[column].unique()

# Convert boolean
data["class"] = data["class"].astype(int)
data.dtypes

# Check result
data.head(5)

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   0   0   1   0   0      1
1   1   1   1   1   0   0   0   1   0      1
2   1   1   1   1   0   0   0   0   1      1
3   1   1   1   1   0   0   0   2   2      1
4   1   1   1   1   0   0   2   0   2      1

In [21]:
# 4. Separate the inputs and output.
data_x = data[data.columns.difference(["class"])]
data_y = data["class"]

In [6]:
# 5. Normalize the input data.
data_x = tf.keras.utils.normalize(data_x, axis=1)
data_x

,BL,BM,BR,ML,MM,MR,TL,TM,TR
0,0.447214,0.000000,0.000000,0.447214,0.000000,0.000000,0.447214,0.447214,0.447214
1,0.000000,0.447214,0.000000,0.447214,0.000000,0.000000,0.447214,0.447214,0.447214
2,0.000000,0.000000,0.447214,0.447214,0.000000,0.000000,0.447214,0.447214,0.447214
3,0.000000,0.577350,0.577350,0.288675,0.000000,0.000000,0.288675,0.288675,0.288675
4,0.577350,0.000000,0.577350,0.288675,0.000000,0.000000,0.288675,0.288675,0.288675
...,...,...,...,...,...,...,...,...,...
953,0.000000,0.447214,0.447214,0.447214,0.000000,0.000000,0.000000,0.447214,0.447214
954,0.447214,0.000000,0.447214,0.447214,0.447214,0.000000,0.000000,0.447214,0.000000
955,0.447214,0.000000,0.447214,0.447214,0.000000,0.447214,0.000000,0.447214,0.000000
956,0.447214,0.000000,0.447214,0.000000,0.447214,0.447214,0.000000,0.447214,0.000000
957,0.000000,0.447214,0.447214,0.447214,0.447214,0.000000,0.000000,0.000000,0.447214

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [7]:
# 1. Split the training and test data.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2)

In [8]:
# 2. Create a Sequential model.
model = tf.keras.models.Sequential()

In [9]:
# 3. Add several layers to your model.
model.add(tf.keras.layers.Flatten())

# Hidden layer  - 128 units with default activation function
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
# loss: 0.5821 - accuracy: 0.685
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
# loss: 0.5582 - accuracy: 0.7010
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
# loss: 0.5243 - accuracy: 0.7363 -- more layers doesnt help

# Hidden layer with number of desired output with probability distr.
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

In [10]:
# 4. Compile the model using adam as the optimizer and sparse_categorical_crossentropy as the loss function.

# Define parameters for the training model. Loss = degree of error
model.compile(optimizer="adam",
             loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])

In [11]:
# 5. Fit the training data.
# model.fit(X_train, y_train, epochs=3)
## loss: 0.5243 - accuracy: 0.7363
# model.fit(X_train, y_train, epochs=6)
# # loss: 0.3037 - accuracy: 0.8877
# model.fit(X_train, y_train, epochs=10)
# loss: 0.1092 - accuracy: 0.9661
model.fit(X_train, y_train, epochs=8)
# 5ms/step - loss: 0.1601 - accuracy: 0.9517 -- more layers doesnt help

Epoch 1/8
WARNING:tensorflow:Layer flatten is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

24/24 [==============================] - 0s 5ms/step - loss: 0.6464 - accuracy: 0.6410
Epoch 2/8
24/24 [==============================] - 0s 8ms/step - loss: 0.6045 - accuracy: 0.6436
Epoch 3/8
24/24 [==============================] - 0s 6ms/step - loss: 0.5351 - accuracy: 0.7167
Epoch 4/8
24/24 [==============================] - 0s 5ms/step - loss: 0.4570 - accuracy: 0.7624
Epoch 5/8
24/24 [==============================] - 0s 5ms/step - loss: 0.3625 - accuracy: 0.8629
Epoch 6/8
24/24 [==============================] - 0s 6ms/step - loss: 0.2913 - accuracy: 0.8956
Epoch 7/8
24/24 [==============================] - 0s 7ms/step - loss: 0.2369 - accuracy: 0.9217
Epoch 8/8
24/24 [==============================] - 0s 4ms/step - loss: 0.1705 - accuracy: 0.9543

In [12]:
# 6. Evaluate your neural network model with the test data.
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss, val_acc)

6/6 [==============================] - 0s 4ms/step - loss: 0.1600 - accuracy: 0.9531
0.16000615060329437 0.953125

In [13]:
# 7. Save your model as tic-tac-toe.model.
model.save("tic-tac-toe.model")

WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: tic-tac-toe.model/assets

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [14]:
# Load saved model
new_model = tf.keras.models.load_model("tic-tac-toe.model")

In [15]:
# Make predictions on a few random rows
predictions = new_model.predict(X_test)
print(predictions)

[[1.55565524e-02 9.84443426e-01]
 [9.55777943e-01 4.42219898e-02]
 [9.85471532e-02 9.01452839e-01]
 [6.85247183e-01 3.14752877e-01]
 [6.50832355e-01 3.49167705e-01]
 [1.89600345e-02 9.81040001e-01]
 [9.42942739e-01 5.70572875e-02]
 [1.62750315e-02 9.83724892e-01]
 [6.02869131e-03 9.93971288e-01]
 [4.21712350e-04 9.99578297e-01]
 [9.48553085e-01 5.14469035e-02]
 [5.51182568e-01 4.48817521e-01]
 [9.70379412e-01 2.96205524e-02]
 [6.53675437e-01 3.46324533e-01]
 [1.82902568e-03 9.98170972e-01]
 [2.31305912e-01 7.68694103e-01]
 [9.23355103e-01 7.66449198e-02]
 [8.53427034e-03 9.91465688e-01]
 [9.40250233e-03 9.90597427e-01]
 [6.76822674e-04 9.99323249e-01]
 [1.67450551e-02 9.83254910e-01]
 [6.97534382e-02 9.30246532e-01]
 [6.92217378e-04 9.99307752e-01]
 [3.11999838e-03 9.96880054e-01]
 [2.16901638e-02 9.78309870e-01]
 [9.69917297e-01 3.00827045e-02]
 [9.87696834e-03 9.90122974e-01]
 [7.78200198e-03 9.92218018e-01]
 [1.37030184e-02 9.86297011e-01]
 [2.81990375e-02 9.71800923e-01]
 [2.04017516e-02 9.79598224e-01]
 [1.46048237e-02 9.85395193e-01]
 [7.09394634e-01 2.90605336e-01]
 [9.90484655e-03 9.90095139e-01]
 [8.44178617e-01 1.55821353e-01]
 [3.14894156e-03 9.96851027e-01]
 [1.47499209e-02 9.85250056e-01]
 [9.29499984e-01 7.05000162e-02]
 [1.06551975e-03 9.98934448e-01]
 [4.07777756e-01 5.92222273e-01]
 [6.22084131e-03 9.93779123e-01]
 [9.27576661e-01 7.24233314e-02]
 [2.81812018e-03 9.97181892e-01]
 [9.18168724e-01 8.18313286e-02]
 [8.70071769e-01 1.29928216e-01]
 [1.67565066e-02 9.83243525e-01]
 [9.82863724e-01 1.71363465e-02]
 [7.99134746e-03 9.92008686e-01]
 [6.10429585e-01 3.89570415e-01]
 [9.85949457e-01 1.40505685e-02]
 [5.29897809e-01 4.70102191e-01]
 [9.00078177e-01 9.99218374e-02]
 [8.11958015e-01 1.88041925e-01]
 [8.74698400e-01 1.25301600e-01]
 [1.56205567e-03 9.98437941e-01]
 [9.63208735e-01 3.67912985e-02]
 [9.19873297e-01 8.01266953e-02]
 [8.88254866e-03 9.91117477e-01]
 [3.35580371e-02 9.66441989e-01]
 [8.82265925e-01 1.17734104e-01]
 [9.51024294e-01 4.89756763e-02]
 [9.29096192e-02 9.07090425e-01]
 [1.33686187e-02 9.86631334e-01]
 [8.90334725e-01 1.09665282e-01]
 [2.17328928e-02 9.78267074e-01]
 [3.54115963e-02 9.64588463e-01]
 [4.40438930e-03 9.95595634e-01]
 [1.12472437e-02 9.88752723e-01]
 [6.35911571e-03 9.93640840e-01]
 [1.57333650e-02 9.84266579e-01]
 [1.36404159e-02 9.86359656e-01]
 [1.00272503e-02 9.89972711e-01]
 [1.15625840e-02 9.88437355e-01]
 [9.78617013e-01 2.13830490e-02]
 [4.86863457e-04 9.99513149e-01]
 [3.92988026e-02 9.60701168e-01]
 [2.52421293e-03 9.97475803e-01]
 [1.55031094e-02 9.84496951e-01]
 [8.25263441e-01 1.74736574e-01]
 [9.35374200e-01 6.46257401e-02]
 [3.36082256e-03 9.96639132e-01]
 [1.07814651e-02 9.89218533e-01]
 [8.84696282e-03 9.91153061e-01]
 [4.27698046e-02 9.57230151e-01]
 [1.84498332e-03 9.98155057e-01]
 [4.22827043e-02 9.57717240e-01]
 [8.89671501e-03 9.91103292e-01]
 [3.00161801e-02 9.69983816e-01]
 [9.15655434e-01 8.43445137e-02]
 [9.84476507e-01 1.55235529e-02]
 [9.62354898e-01 3.76450829e-02]
 [5.23281574e-01 4.76718336e-01]
 [5.28950151e-03 9.94710445e-01]
 [5.67625701e-01 4.32374239e-01]
 [9.06841736e-03 9.90931511e-01]
 [3.87420203e-03 9.96125758e-01]
 [5.41967332e-01 4.58032638e-01]
 [6.34344341e-03 9.93656576e-01]
 [1.00640776e-02 9.89935935e-01]
 [1.59199592e-02 9.84080017e-01]
 [4.07510786e-04 9.99592483e-01]
 [4.51499186e-02 9.54850078e-01]
 [1.44799752e-02 9.85519946e-01]
 [1.24294527e-01 8.75705481e-01]
 [1.64876789e-01 8.35123181e-01]
 [5.72700620e-01 4.27299410e-01]
 [3.79890688e-02 9.62010920e-01]
 [1.05610296e-01 8.94389689e-01]
 [7.75392175e-01 2.24607840e-01]
 [8.93505335e-01 1.06494650e-01]
 [9.11630541e-02 9.08836961e-01]
 [3.46499942e-02 9.65350032e-01]
 [6.93311403e-03 9.93066907e-01]
 [3.75514440e-02 9.62448537e-01]
 [9.15915612e-03 9.90840793e-01]
 [7.88421631e-01 2.11578429e-01]
 [3.08720488e-03 9.96912718e-01]
 [9.53679979e-01 4.63200361e-02]
 [2.87572690e-03 9.97124255e-01]
 [9.29551065e-01 7.04489127e-02]
 [5.50792599e-03 9.94492054e-01]
 [2.34517336e-01 7.65482605e-01]
 [6.29431754e-03 9.93705690e-01]
 [4.17865114e-03 9.95821357e-01]
 [3.30828456e-03 9.96691704e-01]
 [8.32051411e-03 9.91679490e-01]
 [1.41652729e-02 9.85834777e-01]
 [7.31651112e-02 9.26834881e-01]
 [3.43394950e-02 9.65660512e-01]
 [6.67688786e-04 9.99332249e-01]
 [1.40100392e-03 9.98598993e-01]
 [5.75440601e-02 9.42455947e-01]
 [4.39079152e-03 9.95609224e-01]
 [9.87449169e-01 1.25508467e-02]
 [9.74087894e-01 2.59121004e-02]
 [1.34267146e-02 9.86573339e-01]
 [5.18042943e-04 9.99481976e-01]
 [9.59824249e-02 9.04017568e-01]
 [1.03130668e-01 8.96869302e-01]
 [8.01801324e-01 1.98198676e-01]
 [8.80439021e-03 9.91195560e-01]
 [8.84204566e-01 1.15795396e-01]
 [6.42989995e-03 9.93570089e-01]
 [4.11001313e-03 9.95889962e-01]
 [1.82885621e-02 9.81711388e-01]
 [1.19508738e-02 9.88049090e-01]
 [1.72073748e-02 9.82792675e-01]
 [1.14005603e-01 8.85994375e-01]
 [9.49603379e-01 5.03966324e-02]
 [3.89374606e-03 9.96106207e-01]
 [1.19109470e-02 9.88089025e-01]
 [8.99692595e-01 1.00307338e-01]
 [9.55752671e-01 4.42472696e-02]
 [4.40038964e-02 9.55996156e-01]
 [2.32902225e-02 9.76709843e-01]
 [9.61559772e-01 3.84401940e-02]
 [2.11719703e-02 9.78828013e-01]
 [2.32262001e-03 9.97677386e-01]
 [9.97602269e-02 9.00239766e-01]
 [1.31215621e-03 9.98687804e-01]
 [1.91789009e-02 9.80821133e-01]
 [1.67584252e-02 9.83241558e-01]
 [3.78386080e-02 9.62161422e-01]
 [3.05672437e-02 9.69432712e-01]
 [9.56192374e-01 4.38075773e-02]
 [2.46164650e-02 9.75383580e-01]
 [6.41750574e-01 3.58249426e-01]
 [1.78904645e-02 9.82109547e-01]
 [1.78186875e-02 9.82181311e-01]
 [2.77689332e-03 9.97223139e-01]
 [3.86297517e-02 9.61370230e-01]
 [1.18685123e-02 9.88131523e-01]
 [1.18668675e-02 9.88133132e-01]
 [8.71080160e-02 9.12891984e-01]
 [4.18895157e-03 9.95811105e-01]
 [6.88604355e-01 3.11395645e-01]
 [5.03347702e-02 9.49665248e-01]
 [9.91009176e-04 9.99009013e-01]
 [1.80617869e-02 9.81938243e-01]
 [4.89033700e-04 9.99511003e-01]
 [1.10360924e-02 9.88963842e-01]
 [2.82690302e-02 9.71730888e-01]
 [2.70902812e-01 7.29097188e-01]
 [7.47477174e-01 2.52522826e-01]
 [2.67512444e-03 9.97324824e-01]
 [4.50430065e-02 9.54957008e-01]
 [3.05785006e-03 9.96942103e-01]
 [9.08758581e-01 9.12413672e-02]
 [2.03063036e-03 9.97969329e-01]
 [6.22755699e-02 9.37724411e-01]
 [3.66331190e-01 6.33668840e-01]
 [5.33087738e-02 9.46691215e-01]]

In [16]:
# Check if the predictions are correct.
np.argmax(predictions[0])

1

In [17]:
data.head(1)

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   0   0   1   0   0      1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [18]:
# I added the code in the assignments above

**Which approach(es) did you find helpful to improve your model performance?**

In [19]:
"""
I added more 3 layers and changed epochs to 8
"""

'\nI added more 3 layers and changed epochs to 8\n'